-- Seed providers batch 26/26 from INITIAL_PROVIDERS (deterministic prototype cooperative members)
-- Generated: 2026-09-03T17:23:00.686Z
-- Batch 26: providers 2501-2525 of 2525 (25 providers)
-- Total providers: 2525 (this batch: 25)
-- Synthetic prototype members are marked as "Synthetic prototype cooperative member — not a real person."
-- Idempotent: ON CONFLICT (id) DO UPDATE
-- Source: src/db/seed_providers.sql (split into 26 batches for Supabase SQL Editor)
-- Independently executable: paste this entire file into Supabase SQL Editor and run
BEGIN;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-move-01-02',
  'Rahul Ali',
  'Moving & Heavy Lifting Assistance — Siliguri (Prototype)',
  4.94,
  59,
  89,
  10,
  'https://images.unsplash.com/photo-1500000082839?w=300&auto=format&fit=crop&q=80',
  '+91 9849282839',
  'siliguri.move-01.02@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7205,"lng":88.3785}'::jsonb,
  799,
  799,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Moving & Heavy Lifting Assistance', 'Moving Assistance']::text[],
  ARRAY['Moving & Heavy Lifting Assistance']::text[],
  'Synthetic prototype cooperative member for Moving & Heavy Lifting Assistance in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-move-01-03',
  'Aarav Ali',
  'Moving & Heavy Lifting Assistance — Siliguri (Prototype)',
  4.5,
  60,
  90,
  2,
  'https://images.unsplash.com/photo-1500000082840?w=300&auto=format&fit=crop&q=80',
  '+91 9849282840',
  'siliguri.move-01.03@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7211,"lng":88.3785}'::jsonb,
  799,
  799,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Moving & Heavy Lifting Assistance', 'Moving Assistance']::text[],
  ARRAY['Moving & Heavy Lifting Assistance']::text[],
  'Synthetic prototype cooperative member for Moving & Heavy Lifting Assistance in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-move-01-04',
  'Vivaan Ali',
  'Moving & Heavy Lifting Assistance — Siliguri (Prototype)',
  4.51,
  61,
  91,
  3,
  'https://images.unsplash.com/photo-1500000082841?w=300&auto=format&fit=crop&q=80',
  '+91 9849282841',
  'siliguri.move-01.04@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7217,"lng":88.3785}'::jsonb,
  799,
  799,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Moving & Heavy Lifting Assistance', 'Moving Assistance']::text[],
  ARRAY['Moving & Heavy Lifting Assistance']::text[],
  'Synthetic prototype cooperative member for Moving & Heavy Lifting Assistance in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-move-01-05',
  'Aditya Ali',
  'Moving & Heavy Lifting Assistance — Siliguri (Prototype)',
  4.52,
  62,
  92,
  4,
  'https://images.unsplash.com/photo-1500000082842?w=300&auto=format&fit=crop&q=80',
  '+91 9849282842',
  'siliguri.move-01.05@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7223,"lng":88.3785}'::jsonb,
  799,
  799,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Moving & Heavy Lifting Assistance', 'Moving Assistance']::text[],
  ARRAY['Moving & Heavy Lifting Assistance']::text[],
  'Synthetic prototype cooperative member for Moving & Heavy Lifting Assistance in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-move-01-06',
  'Arjun Ali',
  'Moving & Heavy Lifting Assistance — Siliguri (Prototype)',
  4.53,
  63,
  93,
  5,
  'https://images.unsplash.com/photo-1500000082843?w=300&auto=format&fit=crop&q=80',
  '+91 9849282843',
  'siliguri.move-01.06@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7229,"lng":88.3785}'::jsonb,
  799,
  799,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Moving & Heavy Lifting Assistance', 'Moving Assistance']::text[],
  ARRAY['Moving & Heavy Lifting Assistance']::text[],
  'Synthetic prototype cooperative member for Moving & Heavy Lifting Assistance in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-move-01-07',
  'Sai Ali',
  'Moving & Heavy Lifting Assistance — Siliguri (Prototype)',
  4.54,
  64,
  94,
  6,
  'https://images.unsplash.com/photo-1500000082844?w=300&auto=format&fit=crop&q=80',
  '+91 9849282844',
  'siliguri.move-01.07@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7235,"lng":88.3785}'::jsonb,
  799,
  799,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Moving & Heavy Lifting Assistance', 'Moving Assistance']::text[],
  ARRAY['Moving & Heavy Lifting Assistance']::text[],
  'Synthetic prototype cooperative member for Moving & Heavy Lifting Assistance in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-move-01-08',
  'Reyansh Ali',
  'Moving & Heavy Lifting Assistance — Siliguri (Prototype)',
  4.55,
  65,
  95,
  7,
  'https://images.unsplash.com/photo-1500000082845?w=300&auto=format&fit=crop&q=80',
  '+91 9849282845',
  'siliguri.move-01.08@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7241,"lng":88.3785}'::jsonb,
  799,
  799,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Moving & Heavy Lifting Assistance', 'Moving Assistance']::text[],
  ARRAY['Moving & Heavy Lifting Assistance']::text[],
  'Synthetic prototype cooperative member for Moving & Heavy Lifting Assistance in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-move-01-09',
  'Ayaan Ali',
  'Moving & Heavy Lifting Assistance — Siliguri (Prototype)',
  4.56,
  66,
  96,
  8,
  'https://images.unsplash.com/photo-1500000082846?w=300&auto=format&fit=crop&q=80',
  '+91 9849282846',
  'siliguri.move-01.09@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7247,"lng":88.3785}'::jsonb,
  799,
  799,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Moving & Heavy Lifting Assistance', 'Moving Assistance']::text[],
  ARRAY['Moving & Heavy Lifting Assistance']::text[],
  'Synthetic prototype cooperative member for Moving & Heavy Lifting Assistance in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-move-01-10',
  'Kabir Chopra',
  'Moving & Heavy Lifting Assistance — Siliguri (Prototype)',
  4.75,
  70,
  300,
  9,
  'https://images.unsplash.com/photo-1500000064250?w=300&auto=format&fit=crop&q=80',
  '+91 9857964250',
  'siliguri.move-01.10@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7271,"lng":88.4223}'::jsonb,
  799,
  799,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Moving & Heavy Lifting Assistance', 'Moving Assistance']::text[],
  ARRAY['Moving & Heavy Lifting Assistance']::text[],
  'Synthetic prototype cooperative member for Moving & Heavy Lifting Assistance in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-clean-01-04',
  'Reyansh Menon',
  'Society Common Area Sanitization — Siliguri (Prototype)',
  4.5,
  105,
  335,
  2,
  'https://images.unsplash.com/photo-1500000040285?w=300&auto=format&fit=crop&q=80',
  '+91 9842440285',
  'siliguri.soc-clean-01.04@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7481,"lng":88.4037}'::jsonb,
  2499,
  2499,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Society Common Area Sanitization', 'Apartment Maintenance']::text[],
  ARRAY['Society Common Area Sanitization']::text[],
  'Synthetic prototype cooperative member for Society Common Area Sanitization in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-clean-01-05',
  'Ayaan Menon',
  'Society Common Area Sanitization — Siliguri (Prototype)',
  4.51,
  106,
  336,
  3,
  'https://images.unsplash.com/photo-1500000040286?w=300&auto=format&fit=crop&q=80',
  '+91 9842440286',
  'siliguri.soc-clean-01.05@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7487,"lng":88.4037}'::jsonb,
  2499,
  2499,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Society Common Area Sanitization', 'Apartment Maintenance']::text[],
  ARRAY['Society Common Area Sanitization']::text[],
  'Synthetic prototype cooperative member for Society Common Area Sanitization in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-clean-01-06',
  'Krishna Menon',
  'Society Common Area Sanitization — Siliguri (Prototype)',
  4.52,
  107,
  337,
  4,
  'https://images.unsplash.com/photo-1500000040287?w=300&auto=format&fit=crop&q=80',
  '+91 9842440287',
  'siliguri.soc-clean-01.06@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7493,"lng":88.4037}'::jsonb,
  2499,
  2499,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Society Common Area Sanitization', 'Apartment Maintenance']::text[],
  ARRAY['Society Common Area Sanitization']::text[],
  'Synthetic prototype cooperative member for Society Common Area Sanitization in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-clean-01-07',
  'Ishaan Menon',
  'Society Common Area Sanitization — Siliguri (Prototype)',
  4.53,
  108,
  338,
  5,
  'https://images.unsplash.com/photo-1500000040288?w=300&auto=format&fit=crop&q=80',
  '+91 9842440288',
  'siliguri.soc-clean-01.07@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7499,"lng":88.4037}'::jsonb,
  2499,
  2499,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Society Common Area Sanitization', 'Apartment Maintenance']::text[],
  ARRAY['Society Common Area Sanitization']::text[],
  'Synthetic prototype cooperative member for Society Common Area Sanitization in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-clean-01-08',
  'Rohan Menon',
  'Society Common Area Sanitization — Siliguri (Prototype)',
  4.54,
  109,
  339,
  6,
  'https://images.unsplash.com/photo-1500000040289?w=300&auto=format&fit=crop&q=80',
  '+91 9842440289',
  'siliguri.soc-clean-01.08@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7505,"lng":88.4037}'::jsonb,
  2499,
  2499,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Society Common Area Sanitization', 'Apartment Maintenance']::text[],
  ARRAY['Society Common Area Sanitization']::text[],
  'Synthetic prototype cooperative member for Society Common Area Sanitization in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-clean-01-09',
  'Kabir Menon',
  'Society Common Area Sanitization — Siliguri (Prototype)',
  4.55,
  110,
  340,
  7,
  'https://images.unsplash.com/photo-1500000040290?w=300&auto=format&fit=crop&q=80',
  '+91 9842440290',
  'siliguri.soc-clean-01.09@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7511,"lng":88.4037}'::jsonb,
  2499,
  2499,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Society Common Area Sanitization', 'Apartment Maintenance']::text[],
  ARRAY['Society Common Area Sanitization']::text[],
  'Synthetic prototype cooperative member for Society Common Area Sanitization in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-clean-01-10',
  'Aditya Pillai',
  'Society Common Area Sanitization — Siliguri (Prototype)',
  4.62,
  182,
  412,
  5,
  'https://images.unsplash.com/photo-1500000058762?w=300&auto=format&fit=crop&q=80',
  '+91 9823958762',
  'siliguri.soc-clean-01.10@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7343,"lng":88.4115}'::jsonb,
  2499,
  2499,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Society Common Area Sanitization', 'Apartment Maintenance']::text[],
  ARRAY['Society Common Area Sanitization']::text[],
  'Synthetic prototype cooperative member for Society Common Area Sanitization in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-event-01-02',
  'Aryan Iyer',
  'Community Event Sound & Electrical Setup — Siliguri (Prototype)',
  4.87,
  122,
  152,
  3,
  'https://images.unsplash.com/photo-1500000041302?w=300&auto=format&fit=crop&q=80',
  '+91 9820841302',
  'siliguri.soc-event-01.02@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.6983,"lng":88.3785}'::jsonb,
  1800,
  1800,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Community Event Sound & Electrical Setup', 'Community Event Support']::text[],
  ARRAY['Community Event Sound & Electrical Setup']::text[],
  'Synthetic prototype cooperative member for Community Event Sound & Electrical Setup in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-event-01-03',
  'Sahil Iyer',
  'Community Event Sound & Electrical Setup — Siliguri (Prototype)',
  4.86,
  121,
  151,
  2,
  'https://images.unsplash.com/photo-1500000041301?w=300&auto=format&fit=crop&q=80',
  '+91 9820841301',
  'siliguri.soc-event-01.03@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.6977,"lng":88.3785}'::jsonb,
  1800,
  1800,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Community Event Sound & Electrical Setup', 'Community Event Support']::text[],
  ARRAY['Community Event Sound & Electrical Setup']::text[],
  'Synthetic prototype cooperative member for Community Event Sound & Electrical Setup in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-event-01-04',
  'Riya Iyer',
  'Community Event Sound & Electrical Setup — Siliguri (Prototype)',
  4.85,
  120,
  150,
  10,
  'https://images.unsplash.com/photo-1500000041300?w=300&auto=format&fit=crop&q=80',
  '+91 9820841300',
  'siliguri.soc-event-01.04@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.6971,"lng":88.3785}'::jsonb,
  1800,
  1800,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Community Event Sound & Electrical Setup', 'Community Event Support']::text[],
  ARRAY['Community Event Sound & Electrical Setup']::text[],
  'Synthetic prototype cooperative member for Community Event Sound & Electrical Setup in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-event-01-05',
  'Meera Iyer',
  'Community Event Sound & Electrical Setup — Siliguri (Prototype)',
  4.84,
  119,
  149,
  9,
  'https://images.unsplash.com/photo-1500000041299?w=300&auto=format&fit=crop&q=80',
  '+91 9820841299',
  'siliguri.soc-event-01.05@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7565,"lng":88.3785}'::jsonb,
  1800,
  1800,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Community Event Sound & Electrical Setup', 'Community Event Support']::text[],
  ARRAY['Community Event Sound & Electrical Setup']::text[],
  'Synthetic prototype cooperative member for Community Event Sound & Electrical Setup in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-event-01-06',
  'Ira Iyer',
  'Community Event Sound & Electrical Setup — Siliguri (Prototype)',
  4.83,
  118,
  148,
  8,
  'https://images.unsplash.com/photo-1500000041298?w=300&auto=format&fit=crop&q=80',
  '+91 9820841298',
  'siliguri.soc-event-01.06@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7559,"lng":88.3785}'::jsonb,
  1800,
  1800,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Community Event Sound & Electrical Setup', 'Community Event Support']::text[],
  ARRAY['Community Event Sound & Electrical Setup']::text[],
  'Synthetic prototype cooperative member for Community Event Sound & Electrical Setup in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-event-01-07',
  'Kavya Iyer',
  'Community Event Sound & Electrical Setup — Siliguri (Prototype)',
  4.82,
  117,
  147,
  7,
  'https://images.unsplash.com/photo-1500000041297?w=300&auto=format&fit=crop&q=80',
  '+91 9820841297',
  'siliguri.soc-event-01.07@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7553,"lng":88.3785}'::jsonb,
  1800,
  1800,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Community Event Sound & Electrical Setup', 'Community Event Support']::text[],
  ARRAY['Community Event Sound & Electrical Setup']::text[],
  'Synthetic prototype cooperative member for Community Event Sound & Electrical Setup in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-event-01-08',
  'Sneha Iyer',
  'Community Event Sound & Electrical Setup — Siliguri (Prototype)',
  4.81,
  116,
  146,
  6,
  'https://images.unsplash.com/photo-1500000041296?w=300&auto=format&fit=crop&q=80',
  '+91 9820841296',
  'siliguri.soc-event-01.08@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7547,"lng":88.3785}'::jsonb,
  1800,
  1800,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Community Event Sound & Electrical Setup', 'Community Event Support']::text[],
  ARRAY['Community Event Sound & Electrical Setup']::text[],
  'Synthetic prototype cooperative member for Community Event Sound & Electrical Setup in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-event-01-09',
  'Priya Iyer',
  'Community Event Sound & Electrical Setup — Siliguri (Prototype)',
  4.8,
  115,
  145,
  5,
  'https://images.unsplash.com/photo-1500000041295?w=300&auto=format&fit=crop&q=80',
  '+91 9820841295',
  'siliguri.soc-event-01.09@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.7541,"lng":88.3785}'::jsonb,
  1800,
  1800,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Community Event Sound & Electrical Setup', 'Community Event Support']::text[],
  ARRAY['Community Event Sound & Electrical Setup']::text[],
  'Synthetic prototype cooperative member for Community Event Sound & Electrical Setup in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
INSERT INTO public.providers (id, name, title, rating, rating_count, completed_jobs, experience_years, avatar, phone, email, location, coords, base_price, starting_price, availability, is_coop_member, coop_badge, coop_dividend_score, verifications, service_categories, skills, bio, recent_reviews) VALUES (
  'prov-synthetic-siliguri-soc-event-01-10',
  'Sunil Das',
  'Community Event Sound & Electrical Setup — Siliguri (Prototype)',
  4.51,
  51,
  281,
  3,
  'https://images.unsplash.com/photo-1500000023431?w=300&auto=format&fit=crop&q=80',
  '+91 9823723431',
  'siliguri.soc-event-01.10@zolve-coop.org',
  'Siliguri Hub — 50km coverage',
  '{"lat":26.715700000000002,"lng":88.4187}'::jsonb,
  1800,
  1800,
  'Available Today',
  true,
  'Cooperative Member — Prototype',
  'Prototype Tier',
  '{"identity":true,"skill":true,"phone":true,"background":true,"coopMember":true}'::jsonb,
  ARRAY['Community Event Sound & Electrical Setup', 'Community Event Support']::text[],
  ARRAY['Community Event Sound & Electrical Setup']::text[],
  'Synthetic prototype cooperative member for Community Event Sound & Electrical Setup in Siliguri (within 50km of 26.73,88.40). Not a real person — for SIH prototype coverage.',
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count,
  completed_jobs = EXCLUDED.completed_jobs,
  experience_years = EXCLUDED.experience_years,
  avatar = EXCLUDED.avatar,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  location = EXCLUDED.location,
  coords = EXCLUDED.coords,
  base_price = EXCLUDED.base_price,
  starting_price = EXCLUDED.starting_price,
  availability = EXCLUDED.availability,
  is_coop_member = EXCLUDED.is_coop_member,
  coop_badge = EXCLUDED.coop_badge,
  coop_dividend_score = EXCLUDED.coop_dividend_score,
  verifications = EXCLUDED.verifications,
  service_categories = EXCLUDED.service_categories,
  skills = EXCLUDED.skills,
  bio = EXCLUDED.bio,
  recent_reviews = EXCLUDED.recent_reviews;
COMMIT;
-- Batch 26 verification:
-- SELECT COUNT(*) FROM public.providers; -- should increase by 25 after this batch
-- Full verification after all batches: SELECT COUNT(*) FROM public.providers; -- Expected: 2525
