-- Seed 21 societies, one per CITY_HUB (20 + Siliguri), embedded in Supabase
insert into public.societies (hub_id, city, state, name, location, manager_name, units, blocks, stats, coords, pincode)
values
('hub-delhi','Delhi NCR','Delhi','Delhi NCR Residency Cooperative','Connaught Place, Central Delhi','Rohan Mehra',380,5,'{"openRequests":9,"completedThisMonth":62,"pendingApproval":5,"emergencyOpen":2}'::jsonb,'{"lat":28.6139,"lng":77.2090}'::jsonb,'110001'),
('hub-gurugram','Gurugram','Haryana','Gurugram Green Valley Cooperative','Cyber City, DLF Phase 3, Gurugram','Sangeeta Rao',340,4,'{"openRequests":7,"completedThisMonth":48,"pendingApproval":3,"emergencyOpen":1}'::jsonb,'{"lat":28.4595,"lng":77.0266}'::jsonb,'122001'),
('hub-mumbai','Mumbai','Maharashtra','Mumbai Seaside Residency','Dadar West, Mumbai','Vikram Deshmukh',420,6,'{"openRequests":11,"completedThisMonth":71,"pendingApproval":6,"emergencyOpen":2}'::jsonb,'{"lat":19.076,"lng":72.8777}'::jsonb,'400001'),
('hub-bengaluru','Bengaluru','Karnataka','Green Valley Residency','Sarjapur Main Road, Bengaluru','Vikram Malhotra',340,4,'{"openRequests":8,"completedThisMonth":54,"pendingApproval":4,"emergencyOpen":1}'::jsonb,'{"lat":12.9716,"lng":77.5946}'::jsonb,'560001'),
('hub-chennai','Chennai','Tamil Nadu','Chennai Marina Cooperative','T Nagar, Chennai','Lakshmanan R',360,5,'{"openRequests":10,"completedThisMonth":58,"pendingApproval":5,"emergencyOpen":1}'::jsonb,'{"lat":13.0827,"lng":80.2707}'::jsonb,'600001'),
('hub-hyderabad','Hyderabad','Telangana','Hyderabad Banjara Residency','Banjara Hills, Hyderabad','Ramesh Goud',350,5,'{"openRequests":9,"completedThisMonth":55,"pendingApproval":4,"emergencyOpen":2}'::jsonb,'{"lat":17.385,"lng":78.4867}'::jsonb,'500001'),
('hub-kolkata','Kolkata','West Bengal','Kolkata Salt Lake Residency','Salt Lake Sector 5, Kolkata','Debashish Roy',330,4,'{"openRequests":8,"completedThisMonth":51,"pendingApproval":4,"emergencyOpen":1}'::jsonb,'{"lat":22.5726,"lng":88.3639}'::jsonb,'700001'),
('hub-ahmedabad','Ahmedabad','Gujarat','Ahmedabad Navrang Residency','Navrangpura, Ahmedabad','Ketan Patel',310,4,'{"openRequests":7,"completedThisMonth":49,"pendingApproval":3,"emergencyOpen":1}'::jsonb,'{"lat":23.0225,"lng":72.5714}'::jsonb,'380001'),
('hub-pune','Pune','Maharashtra','Pune Kothrud Cooperative','Kothrud, Pune','Snehal Kulkarni',340,5,'{"openRequests":8,"completedThisMonth":53,"pendingApproval":4,"emergencyOpen":1}'::jsonb,'{"lat":18.5204,"lng":73.8567}'::jsonb,'411001'),
('hub-surat','Surat','Gujarat','Surat Diamond Residency','Athwa Gate, Surat','Paresh Shah',300,4,'{"openRequests":6,"completedThisMonth":46,"pendingApproval":3,"emergencyOpen":1}'::jsonb,'{"lat":21.1702,"lng":72.8311}'::jsonb,'395001'),
('hub-vizag','Visakhapatnam','Andhra Pradesh','Vizag MVP Residency','MVP Colony, Visakhapatnam','Satyam Reddy',280,3,'{"openRequests":5,"completedThisMonth":42,"pendingApproval":2,"emergencyOpen":1}'::jsonb,'{"lat":17.6868,"lng":83.2185}'::jsonb,'530001'),
('hub-coimbatore','Coimbatore','Tamil Nadu','Coimbatore Greenfields Residency','RS Puram, Coimbatore','Arun Kumar',290,4,'{"openRequests":6,"completedThisMonth":44,"pendingApproval":3,"emergencyOpen":1}'::jsonb,'{"lat":11.0168,"lng":77.0555}'::jsonb,'641001'),
('hub-vadodara','Vadodara','Gujarat','Vadodara Sayaji Residency','Alkapuri, Vadodara','Harsh Mehta',300,4,'{"openRequests":6,"completedThisMonth":45,"pendingApproval":3,"emergencyOpen":1}'::jsonb,'{"lat":22.3072,"lng":73.1812}'::jsonb,'390001'),
('hub-nagpur','Nagpur','Maharashtra','Nagpur Orange City Residency','Civil Lines, Nagpur','Anil Deshmukh',320,4,'{"openRequests":7,"completedThisMonth":47,"pendingApproval":3,"emergencyOpen":1}'::jsonb,'{"lat":21.1458,"lng":79.0882}'::jsonb,'440001'),
('hub-jaipur','Jaipur','Rajasthan','Jaipur Pink City Residency','C Scheme, Jaipur','Mahendra Singh',340,5,'{"openRequests":8,"completedThisMonth":52,"pendingApproval":4,"emergencyOpen":1}'::jsonb,'{"lat":26.9124,"lng":75.7873}'::jsonb,'302001'),
('hub-lucknow','Lucknow','Uttar Pradesh','Lucknow Hazrat Residency','Hazratganj, Lucknow','Farhan Siddiqui',350,5,'{"openRequests":8,"completedThisMonth":54,"pendingApproval":4,"emergencyOpen":2}'::jsonb,'{"lat":26.8467,"lng":80.9462}'::jsonb,'226001'),
('hub-kochi','Kochi','Kerala','Kochi Marine Residency','Kaloor, Kochi','Joseph Thomas',310,4,'{"openRequests":7,"completedThisMonth":48,"pendingApproval":3,"emergencyOpen":1}'::jsonb,'{"lat":9.9312,"lng":76.2673}'::jsonb,'682001'),
('hub-indore','Indore','Madhya Pradesh','Indore Vijay Residency','Vijay Nagar, Indore','Anil Malhotra',330,4,'{"openRequests":7,"completedThisMonth":50,"pendingApproval":3,"emergencyOpen":1}'::jsonb,'{"lat":22.7196,"lng":75.8577}'::jsonb,'452001'),
('hub-patna','Patna','Bihar','Patna Boring Road Residency','Boring Road, Patna','Mithilesh Kumar',300,4,'{"openRequests":6,"completedThisMonth":45,"pendingApproval":3,"emergencyOpen":1}'::jsonb,'{"lat":25.5941,"lng":85.1376}'::jsonb,'800001'),
('hub-bhopal','Bhopal','Madhya Pradesh','Bhopal Lakeview Residency','Arera Colony, Bhopal','Sunita Verma',320,4,'{"openRequests":7,"completedThisMonth":47,"pendingApproval":3,"emergencyOpen":1}'::jsonb,'{"lat":23.2599,"lng":77.4126}'::jsonb,'462001'),
('hub-siliguri','Siliguri','West Bengal','Siliguri Hill Cart Residency','Hill Cart Road, Siliguri','Bikash Thapa',260,3,'{"openRequests":5,"completedThisMonth":40,"pendingApproval":2,"emergencyOpen":1}'::jsonb,'{"lat":26.7271,"lng":88.3953}'::jsonb,'734001')
on conflict (city, name) do update set
  hub_id=excluded.hub_id, state=excluded.state, location=excluded.location,
  manager_name=excluded.manager_name, units=excluded.units, blocks=excluded.blocks,
  stats=excluded.stats, coords=excluded.coords, pincode=excluded.pincode;
